dir:
  rundir: 项目运行路径 #运行释放文件，缓存均在此目录
  bin: ${dir.rundir}Bind/
  mirai: ${dir.rundir}
  bgdir: ${dir.rundir}bg/
  font: ${dir.rundir}font/
  imghc: ${dir.rundir}imgbuffer/
  osuid: ${dir.rundir}Id/
# mirai设置，分别为qq，密码，是否开启自动登录(用于预留debug，正常使用务必开启) 超级管理员（qq号）
mirai:
  qq: 111111
  password: password
  start: true
  superuser:
    - 222222
    - 333333
ppy:
  url: https://osu.ppy.sh/api/v2/ #建议不要修改
  callbackpath: /oauth  #回调监听链接path
  callBackUrl: url #回调完整链接,确保链接可以指向本机ip
  #  oauth信息
  id: 0000
  token: v2token
  v1token: v1token  #注意，v1已被弃用，可以留空，留空不得调用弃用方法
server:
  port: 8000  #监听端口，确保防火墙放行