dir:
  rundir: G:\Desktop\Program\Java\nowbot\data\
  bin: ${dir.rundir}Bind/
  mirai: ${dir.rundir}
  bgdir: ${dir.rundir}bg/
  font: ${dir.rundir}font/
  imghc: ${dir.rundir}imgbuffer/
  osuid: ${dir.rundir}Id/
mirai:
  qq: 3380746395
  password: woshijiqiren!
  start: true
  permission:
    group-blacklist:
      - 928936255
    group-whitelist:
      - 110316460
    friend-blacklist:
    friend-whitelist:
    super-user:
      - 365246692
      - 2480557535
ppy:
  url: https://osu.ppy.sh/api/v2/
  callbackpath: /oauth
  callBackUrl: http://bind.osuoauth.365246692.xyz:20006/oauth
  #  muzi
  id: 6267
  token: A62B4EiTDYEXoPIfqyEVTzPda4ujDQ2FkuXMRGKQ
  v1token: a0d37ce698d6752b5fc65abe99c139cbf433aefc
#  id: 8721
#  token: aeToW0bVoPptuq9mJhYH6bvPI6PQ1otS0oyBFVqB